theme="material-design"
baseURL = "/"
languageCode = "en-us"
title = "何大卫的博客"
MetaDataFormat = "toml"
paginate = 12 # To specify a multiple of 3
# disqusShortname = "Your Disqus Name" # optional
copyright = "© 2016 Copyright 何大卫"

[params]
  description = "没有一个人能全面把握真理" # optional
  # twitter = "何大卫" # optional
  github = "Daltan" # optional
  weibo = "1787835437" # optional
  #weibo = "1787835437" # optional
  #facebook = "Your facebook Name" # optional
  #gplus = "Your Google+ profile name" # optional
  # linkedin = "Your LinkedIn Name" # optional
  # headerCover = "images/headerCover.jpg" # optional 
  # footerCover = "images/footerCover.png" # optional
  # googleAnalyticsUserID = "Your Analytics User Id" # optional

[permalinks]
  # post = "/:year/:month/:day/:title/" # optional